/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See LICENSE.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/*
 * C shim between the wasm2c-generated PAC guest (pac_guest.c, generated by
 * build.rs into OUT_DIR from pac-wasm-guest/pac_guest.wasm) and the Rust
 * backend in mod.rs.
 *
 * Responsibilities:
 *  - own the generated instance struct and the import "module instances"
 *    (plain structs the generated code forward-declares and we define);
 *  - catch wasm traps: every guest entry runs under wasm_rt_impl_try()
 *    (setjmp), and a trap longjmps back here and is returned as a nonzero
 *    wasm_rt_trap_t code instead of aborting the process;
 *  - forward the guest's imports to Rust (`pac2c_rs_*`, defined in mod.rs),
 *    passing the linear memory as an explicit (base, size) pair so every
 *    guest-offset access is bounds-checked in one place on the Rust side.
 *
 * Sandbox/portability notes: the crate builds the wasm-rt runtime with
 * WASM_RT_USE_MMAP=0 (see build.rs), which selects explicit software bounds
 * checks for every linear-memory access instead of mmap'd guard pages. That
 * is the slower option, but it is fully portable (works on 32-bit targets
 * like armv7, where a 4 GiB+guard reservation is impossible) and it needs no
 * process-wide SIGSEGV/vectored-exception handler — something a library
 * should not install. Stack exhaustion is likewise caught by wasm-rt's
 * depth counter rather than a guard page.
 */

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "wasm-rt-exceptions.h" /* wasm_rt_set_unwind_target (used by wasm_rt_impl_try) */
#include "wasm-rt-impl.h"
#include "wasm-rt.h"

#include "pac_guest.h"

/* Rust-implemented host callbacks (mod.rs). `env` is the opaque per-instance
 * host context. Memory is passed as (base, size) at call time because the
 * base pointer moves when the guest grows its memory. */
extern int32_t pac2c_rs_dns_resolve(void* env,
                                    uint8_t* mem,
                                    uint64_t mem_size,
                                    uint32_t ptr,
                                    uint32_t len);
extern int32_t pac2c_rs_dns_resolve_ex(void* env,
                                       uint8_t* mem,
                                       uint64_t mem_size,
                                       uint32_t ptr,
                                       uint32_t len);
extern int32_t pac2c_rs_my_ip(void* env);
extern int32_t pac2c_rs_my_ip_ex(void* env);
extern void pac2c_rs_take_result(void* env,
                                 uint8_t* mem,
                                 uint64_t mem_size,
                                 uint32_t dest);
extern void pac2c_rs_alert(void* env,
                           uint8_t* mem,
                           uint64_t mem_size,
                           uint32_t ptr,
                           uint32_t len);
extern int32_t pac2c_rs_should_interrupt(void* env);

/* One dispatcher for the WASI stubs; `func` is one of the PAC2C_WASI_*
 * ids below (keep in sync with mod.rs). Returns a WASI errno, or
 * PAC2C_WASI_TRAP to make the shim trap the guest. */
extern uint32_t pac2c_rs_wasi(void* env,
                              uint32_t func,
                              uint8_t* mem,
                              uint64_t mem_size,
                              uint64_t a,
                              uint64_t b,
                              uint64_t c,
                              uint64_t d);

/* Keep in sync with mod.rs. */
#define PAC2C_WASI_FD_WRITE 0
#define PAC2C_WASI_ENVIRON_GET 1
#define PAC2C_WASI_ENVIRON_SIZES_GET 2
#define PAC2C_WASI_CLOCK_TIME_GET 3
#define PAC2C_WASI_RANDOM_GET 4
#define PAC2C_WASI_FD_CLOSE 5
#define PAC2C_WASI_FD_FDSTAT_GET 6
#define PAC2C_WASI_FD_SEEK 7
#define PAC2C_WASI_TRAP 0xffffffffu

struct pac2c_instance;

/* The generated code only forward-declares the import "module instances";
 * their layout is ours to define. */
struct w2c_pac__host {
  struct pac2c_instance* inst;
};
struct w2c_wasi__snapshot__preview1 {
  struct pac2c_instance* inst;
};

typedef struct pac2c_instance {
  struct w2c_pac__host host_import;
  struct w2c_wasi__snapshot__preview1 wasi_import;
  w2c_pac__guest module;
  void* env;
} pac2c_instance;

#define PAC2C_MEM(inst) (&(inst)->module.w2c_memory)

/* --------------------------------------------------------------------------
 * Public API consumed by mod.rs.
 */

/* Process-global runtime init (idempotent). With WASM_RT_USE_MMAP=0 this
 * installs no signal handlers. */
void pac2c_runtime_init(void) {
  if (!wasm_rt_is_initialized()) {
    wasm_rt_init();
  }
}

/* Instantiates the guest (runs data segments, no guest start code). Returns
 * NULL with *trap_out set on failure. `max_memory_bytes` caps linear-memory
 * growth on top of the guest's own 64 MiB QuickJS heap limit. */
pac2c_instance* pac2c_instantiate(void* env,
                                  uint64_t max_memory_bytes,
                                  int32_t* trap_out) {
  pac2c_instance* inst = calloc(1, sizeof(pac2c_instance));
  if (!inst) {
    *trap_out = -1;
    return NULL;
  }
  inst->env = env;
  inst->host_import.inst = inst;
  inst->wasi_import.inst = inst;

  wasm_rt_trap_t code = wasm_rt_impl_try();
  if (code != WASM_RT_TRAP_NONE) {
    /* Instantiation of a valid module only traps on allocation failure of
     * the linear memory; nothing further to free safely. */
    free(inst);
    *trap_out = (int32_t)code;
    return NULL;
  }
  wasm2c_pac__guest_instantiate(&inst->module, &inst->host_import,
                                &inst->wasi_import);

  wasm_rt_memory_t* mem = PAC2C_MEM(inst);
  uint64_t max_pages = max_memory_bytes / mem->page_size;
  if (mem->max_pages > max_pages) {
    mem->max_pages = max_pages;
  }
  *trap_out = 0;
  return inst;
}

void pac2c_destroy(pac2c_instance* inst) {
  wasm2c_pac__guest_free(&inst->module);
  free(inst);
}

void pac2c_set_max_memory(pac2c_instance* inst, uint64_t max_memory_bytes) {
  wasm_rt_memory_t* mem = PAC2C_MEM(inst);
  mem->max_pages = max_memory_bytes / mem->page_size;
}

/* Linear memory access for the Rust side. The base pointer is only valid
 * until the next guest call (memory.grow moves it); Rust re-fetches it
 * around every call. */
uint8_t* pac2c_memory_base(pac2c_instance* inst) {
  return PAC2C_MEM(inst)->data;
}

uint64_t pac2c_memory_size(pac2c_instance* inst) {
  return PAC2C_MEM(inst)->size;
}

/* Guest entries. Each returns 0 on success or the nonzero wasm_rt_trap_t
 * code when the guest trapped (after which the instance must be discarded).
 */

int32_t pac2c_alloc(pac2c_instance* inst, uint32_t len, uint32_t* ptr_out) {
  wasm_rt_trap_t code = wasm_rt_impl_try();
  if (code != WASM_RT_TRAP_NONE) {
    return (int32_t)code;
  }
  *ptr_out = w2c_pac__guest_pac_alloc(&inst->module, len);
  return 0;
}

int32_t pac2c_dealloc(pac2c_instance* inst, uint32_t ptr, uint32_t len) {
  wasm_rt_trap_t code = wasm_rt_impl_try();
  if (code != WASM_RT_TRAP_NONE) {
    return (int32_t)code;
  }
  w2c_pac__guest_pac_free(&inst->module, ptr, len);
  return 0;
}

int32_t pac2c_load(pac2c_instance* inst,
                   uint32_t ptr,
                   uint32_t len,
                   uint64_t* packed_out) {
  wasm_rt_trap_t code = wasm_rt_impl_try();
  if (code != WASM_RT_TRAP_NONE) {
    return (int32_t)code;
  }
  *packed_out = w2c_pac__guest_pac_load(&inst->module, ptr, len);
  return 0;
}

int32_t pac2c_find_proxy(pac2c_instance* inst,
                         uint32_t url_ptr,
                         uint32_t url_len,
                         uint32_t host_ptr,
                         uint32_t host_len,
                         uint64_t* packed_out) {
  wasm_rt_trap_t code = wasm_rt_impl_try();
  if (code != WASM_RT_TRAP_NONE) {
    return (int32_t)code;
  }
  *packed_out = w2c_pac__guest_pac_find_proxy(&inst->module, url_ptr, url_len,
                                              host_ptr, host_len);
  return 0;
}

/* --------------------------------------------------------------------------
 * Guest imports: module "pac_host" (see src/pac/wasm_abi.rs).
 */

u32 w2c_pac__host_host_dns_resolve(struct w2c_pac__host* h, u32 ptr, u32 len) {
  wasm_rt_memory_t* mem = PAC2C_MEM(h->inst);
  return (u32)pac2c_rs_dns_resolve(h->inst->env, mem->data, mem->size, ptr,
                                   len);
}

u32 w2c_pac__host_host_dns_resolve_ex(struct w2c_pac__host* h,
                                      u32 ptr,
                                      u32 len) {
  wasm_rt_memory_t* mem = PAC2C_MEM(h->inst);
  return (u32)pac2c_rs_dns_resolve_ex(h->inst->env, mem->data, mem->size, ptr,
                                      len);
}

u32 w2c_pac__host_host_my_ip(struct w2c_pac__host* h) {
  return (u32)pac2c_rs_my_ip(h->inst->env);
}

u32 w2c_pac__host_host_my_ip_ex(struct w2c_pac__host* h) {
  return (u32)pac2c_rs_my_ip_ex(h->inst->env);
}

void w2c_pac__host_host_take_result(struct w2c_pac__host* h, u32 dest) {
  wasm_rt_memory_t* mem = PAC2C_MEM(h->inst);
  pac2c_rs_take_result(h->inst->env, mem->data, mem->size, dest);
}

void w2c_pac__host_host_alert(struct w2c_pac__host* h, u32 ptr, u32 len) {
  wasm_rt_memory_t* mem = PAC2C_MEM(h->inst);
  pac2c_rs_alert(h->inst->env, mem->data, mem->size, ptr, len);
}

u32 w2c_pac__host_host_should_interrupt(struct w2c_pac__host* h) {
  return (u32)pac2c_rs_should_interrupt(h->inst->env);
}

/* --------------------------------------------------------------------------
 * Guest imports: the capability-free WASI stubs (dispatch to mod.rs).
 */

static u32 pac2c_wasi(struct w2c_wasi__snapshot__preview1* w,
                      uint32_t func,
                      uint64_t a,
                      uint64_t b,
                      uint64_t c,
                      uint64_t d) {
  wasm_rt_memory_t* mem = PAC2C_MEM(w->inst);
  uint32_t r =
      pac2c_rs_wasi(w->inst->env, func, mem->data, mem->size, a, b, c, d);
  if (r == PAC2C_WASI_TRAP) {
    wasm_rt_trap(WASM_RT_TRAP_UNREACHABLE); /* does not return */
  }
  return r;
}

u32 w2c_wasi__snapshot__preview1_fd_write(
    struct w2c_wasi__snapshot__preview1* w,
    u32 fd,
    u32 iovs,
    u32 iovs_len,
    u32 nwritten) {
  return pac2c_wasi(w, PAC2C_WASI_FD_WRITE, fd, iovs, iovs_len, nwritten);
}

u32 w2c_wasi__snapshot__preview1_environ_get(
    struct w2c_wasi__snapshot__preview1* w,
    u32 environ_ptr,
    u32 buf) {
  return pac2c_wasi(w, PAC2C_WASI_ENVIRON_GET, environ_ptr, buf, 0, 0);
}

u32 w2c_wasi__snapshot__preview1_environ_sizes_get(
    struct w2c_wasi__snapshot__preview1* w,
    u32 count,
    u32 size) {
  return pac2c_wasi(w, PAC2C_WASI_ENVIRON_SIZES_GET, count, size, 0, 0);
}

u32 w2c_wasi__snapshot__preview1_clock_time_get(
    struct w2c_wasi__snapshot__preview1* w,
    u32 id,
    u64 precision,
    u32 out) {
  return pac2c_wasi(w, PAC2C_WASI_CLOCK_TIME_GET, id, precision, out, 0);
}

u32 w2c_wasi__snapshot__preview1_random_get(
    struct w2c_wasi__snapshot__preview1* w,
    u32 buf,
    u32 len) {
  return pac2c_wasi(w, PAC2C_WASI_RANDOM_GET, buf, len, 0, 0);
}

u32 w2c_wasi__snapshot__preview1_fd_close(
    struct w2c_wasi__snapshot__preview1* w,
    u32 fd) {
  return pac2c_wasi(w, PAC2C_WASI_FD_CLOSE, fd, 0, 0, 0);
}

u32 w2c_wasi__snapshot__preview1_fd_fdstat_get(
    struct w2c_wasi__snapshot__preview1* w,
    u32 fd,
    u32 out) {
  return pac2c_wasi(w, PAC2C_WASI_FD_FDSTAT_GET, fd, out, 0, 0);
}

u32 w2c_wasi__snapshot__preview1_fd_seek(
    struct w2c_wasi__snapshot__preview1* w,
    u32 fd,
    u64 offset,
    u32 whence,
    u32 out) {
  return pac2c_wasi(w, PAC2C_WASI_FD_SEEK, fd, offset, whence, out);
}

void w2c_wasi__snapshot__preview1_proc_exit(
    struct w2c_wasi__snapshot__preview1* w,
    u32 code) {
  (void)w;
  (void)code;
  /* No process to exit inside the sandbox; treat as unreachable. */
  wasm_rt_trap(WASM_RT_TRAP_UNREACHABLE); /* does not return */
}
