parameters:
  - name: target
    type: string
  - name: test
    type: boolean
    default: false

steps:
  - template: authenticate-cargo.yml

  - pwsh: |
      $ErrorActionPreference = "Stop"
      node npm/scripts/build-native.js ${{ parameters.target }}
      if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    displayName: Build Windows addon

  - ${{ if eq(parameters.test, true) }}:
      - pwsh: |
          npm run test:npm
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        displayName: Test Windows addon
