parameters:
  - name: target
    type: string
  - name: test
    type: boolean
    default: false

steps:
  - template: authenticate-cargo.yml

  - bash: |
      set -e
      brew install wabt
      wasm2c --version
      node npm/scripts/build-native.js ${{ parameters.target }}
    displayName: Build macOS addon

  - ${{ if eq(parameters.test, true) }}:
      - script: npm run test:npm
        displayName: Test macOS addon
